"use client";

import { useEffect, useRef } from "react";
import { TARGET_AIS, type TargetAI } from "@/models/common";
import { DEFAULT_COMPILE_OPTIONS, MODIFIER_ACTIONS, type CompileOptions, type CouncilMode, type ExecutionContext, type ModifierAction } from "@/models/options";
import type { ResolvedPrison } from "@/models/prison";
import type { PromptVersion } from "@/models/prompt";
import { modifierChanges } from "@/core/prison-engine/modifiers";
import {
  MODIFIER_LABELS,
  OPTION_VALUE_LABELS,
  TARGET_LABELS,
  TARGET_REASON_LABELS,
  VERSION_TRIGGER_LABELS,
} from "@/templates/ui-labels";
import { cx, relativeTime } from "@/ui/lib/format";
import { EXECUTION_CONTEXT_LABELS, EXECUTION_CONTEXT_OPTIONS } from "@/ui/common/execution-context";
import { COUNCIL_MODE_LABELS } from "@/ui/common/CouncilModePicker";
import { CouncilReviewPanel } from "@/ui/prompt-output/CouncilReviewPanel";
import { PromptHandoff } from "@/ui/participation/PromptHandoff";
import { PromptJourney } from "@/ui/participation/PromptJourney";
import { useI18n, type Translate } from "@/ui/i18n";
import { useVocabulary } from "@/ui/i18n/vocabulary";
import styles from "./PromptOutput.module.css";

function isPressed(options: CompileOptions, action: ModifierAction): boolean {
  switch (action) {
    case "more_technical":
      return options.technicality === "technical";
    case "shorter":
      return options.verbosity === "concise";
    case "longer":
      return options.verbosity === "detailed";
    case "stricter":
      return options.scope === "strict";
    case "freer":
      return options.scope === "open";
    case "toggle_agent":
      return options.agentMode;
    case "toggle_jailbreak":
      return options.jailbreakMode;
  }
}

/** Only the settings that differ from the defaults, so the meta line stays readable. */
function optionSummary(options: CompileOptions, label: (value: string) => string, t: Translate): string[] {
  const parts = [
    options.verbosity !== DEFAULT_COMPILE_OPTIONS.verbosity && label(OPTION_VALUE_LABELS.verbosity[options.verbosity]),
    options.technicality !== DEFAULT_COMPILE_OPTIONS.technicality && label(OPTION_VALUE_LABELS.technicality[options.technicality]),
    options.scope !== DEFAULT_COMPILE_OPTIONS.scope && label(OPTION_VALUE_LABELS.scope[options.scope]),
    options.agentMode && t("Agent modu", "Agent mode", "智能体模式"),
    options.jailbreakMode && t("JB Modu", "JB mode", "JB 模式"),
    options.executionContext !== "chat" && label(EXECUTION_CONTEXT_LABELS[options.executionContext]),
  ].filter((part): part is string => Boolean(part));
  return parts.length ? parts : [t("Varsayılan ayarlar", "Default settings", "默认设置")];
}

function generationLabel(version: PromptVersion, t: Translate): string {
  const generation = version.generation;
  if (!generation) return t("Bu sürümün üretim kaynağı kaydedilmemiş", "The generation source for this version was not recorded", "此版本的生成来源未记录");
  if (generation.source === "ai") {
    const engine = [generation.provider, generation.model].filter(Boolean).join(" · ");
    return engine ? t(`AI ile üretildi · ${engine}`, `Generated with AI · ${engine}`, `由 AI 生成 · ${engine}`) : t("AI ile üretildi", "Generated with AI", "由 AI 生成");
  }
  return generation.source === "local" ? t("Yerel motorla üretildi", "Generated by the local engine", "由本地引擎生成") : t("Prompt derleyicisi ile üretildi", "Generated by the prompt compiler", "由提示词编译器生成");
}

interface PromptOutputProps {
  prison: ResolvedPrison;
  viewVersion: number | null;
  busy: boolean;
  onViewVersion: (version: number) => void;
  onModify: (action: ModifierAction) => void;
  onRetarget: (target: TargetAI) => void;
  onExecutionContext?: (context: ExecutionContext) => void;
  onCouncilMode?: (mode: CouncilMode) => void;
  councilEnabled?: boolean;
  onRegenerate: () => void;
  onRestore: (version: number) => void;
  onRevise?: (feedback: string) => Promise<boolean>;
}

export function PromptOutput({
  prison,
  viewVersion,
  busy,
  onViewVersion,
  onModify,
  onRetarget,
  onExecutionContext,
  onCouncilMode,
  councilEnabled = true,
  onRegenerate,
  onRestore,
  onRevise,
}: PromptOutputProps) {
  const { locale, t } = useI18n();
  const label = useVocabulary();
  const versions = prison.promptVersions;
  const shown: PromptVersion | undefined =
    versions.find((v) => v.version === (viewVersion ?? prison.activeVersion)) ?? versions.at(-1);
  const isActive = shown?.version === prison.activeVersion;
  const tabsRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    tabsRef.current?.scrollTo({ left: tabsRef.current.scrollWidth, behavior: "smooth" });
  }, [versions.length]);

  if (!shown) return null;

  const { critic } = shown;
  const unresolved = critic.issues.filter((issue) => !issue.fixed);
  const warnings = unresolved.filter((issue) => issue.severity !== "low");
  const isJailbreak = shown.options.jailbreakMode;

  return (
    <section className={cx(styles.root, isJailbreak && styles.jailbreakRoot)} aria-label={t("Üretilen prompt", "Generated prompt", "生成的提示词")}>
      <div className={styles.topbar}>
        <div className={styles.tabs} ref={tabsRef} role="tablist" aria-label={t("Prompt sürümleri", "Prompt versions", "提示词版本")}>
          {versions.map((version) => (
            <button
              key={version.version}
              type="button"
              role="tab"
              aria-selected={version.version === shown.version}
              className={cx(
                styles.tab,
                version.version === shown.version && styles.tabSelected,
                version.version === prison.activeVersion && styles.tabActive,
                version.options.jailbreakMode && styles.tabJailbreak,
              )}
              onClick={() => onViewVersion(version.version)}
              title={`${label(VERSION_TRIGGER_LABELS[version.trigger])}${version.note ? ` — ${version.note}` : ""}`}
            >
              {version.options.jailbreakMode ? "JB " : ""}v{version.version}
            </button>
          ))}
        </div>
      </div>

      <div className={styles.meta}>
        <span className={styles.target} lang="en">
          {TARGET_LABELS[shown.resolvedTarget]}
        </span>
        <span>
          {shown.targetAI === "auto" ? "AUTO · " : ""}
          {label(TARGET_REASON_LABELS[shown.targetReason])}
        </span>
        <span className={styles.sep} aria-hidden>
          ·
        </span>
        <span>{optionSummary(shown.options, label, t).join(" · ")}</span>
        <span className={styles.sep} aria-hidden>
          ·
        </span>
        <span>
          {label(VERSION_TRIGGER_LABELS[shown.trigger])}, {relativeTime(shown.createdAt, Date.now(), locale)}
        </span>
      </div>

      {!isActive ? (
        <div className={styles.historyNote}>
          <span>{t(`v${shown.version} görüntüleniyor. Aktif sürüm v${prison.activeVersion}.`, `Viewing v${shown.version}. The active version is v${prison.activeVersion}.`, `正在查看 v${shown.version}。当前生效版本为 v${prison.activeVersion}。`)}</span>
          <button type="button" className="btn" onClick={() => onRestore(shown.version)} disabled={busy}>
            {t("Bu sürüme dön", "Restore this version", "恢复此版本")}
          </button>
        </div>
      ) : null}

      {isJailbreak && (
        <div className={styles.jbBanner}>
          <strong>{t("JB Modu Aktif:", "JB mode active:", "JB 模式已启用：")}</strong> {generationLabel(shown, t)}. {t("Hedef AI:", "Target AI:", "目标 AI：")} {TARGET_LABELS[shown.resolvedTarget]}.
        </div>
      )}

      {shown.councilReview ? <CouncilReviewPanel review={shown.councilReview} /> : null}

      <pre className={cx(styles.prompt, busy && styles.dimmed, isJailbreak && styles.jbPrompt)} tabIndex={0} aria-label={t("Prompt metni", "Prompt text", "提示词文本")}>
        {shown.text}
      </pre>

      <PromptHandoff
        text={shown.text}
        version={shown.version}
        target={shown.resolvedTarget}
        context={shown.options.executionContext ?? "chat"}
        active={isActive}
        busy={busy}
        onRevise={onRevise}
      />
      <PromptJourney stage="ready" councilEvidence={Boolean(shown.councilReview)} compact />

      <div className={styles.toolbar} role="toolbar" aria-label={t("Prompt ayarları", "Prompt settings", "提示词设置")}>
        {MODIFIER_ACTIONS.map((action) => (
          <button
            key={action}
            type="button"
            className={cx("btn", action === "toggle_jailbreak" && shown.options.jailbreakMode && styles.btnJailbreakActive)}
            aria-pressed={isPressed(shown.options, action)}
            disabled={busy || !isActive || !modifierChanges(prison.compileOptions, action)}
            onClick={() => onModify(action)}
          >
            {label(MODIFIER_LABELS[action])}
          </button>
        ))}
        <label className={styles.targetSelect}>
          <span className="label">{t("Hedef AI", "Target AI", "目标 AI")}</span>
          <select
            value={shown.targetAI}
            disabled={busy || !isActive}
            onChange={(e) => onRetarget(e.target.value as TargetAI)}
            aria-label={t("Hedef AI değiştir", "Change target AI", "更改目标 AI")}
          >
            {TARGET_AIS.map((target) => (
              <option key={target} value={target}>
                {TARGET_LABELS[target]}
              </option>
            ))}
          </select>
        </label>
        {onExecutionContext ? (
          <label className={styles.targetSelect}>
            <span className="label">{t("Kullanım", "Use in", "使用场景")}</span>
            <select value={shown.options.executionContext ?? "chat"} disabled={busy || !isActive} onChange={(e) => onExecutionContext(e.target.value as ExecutionContext)} aria-label={t("Promptun kullanım ortamını değiştir", "Change where the prompt will be used", "更改提示词使用场景")}>
              {EXECUTION_CONTEXT_OPTIONS.map((option) => <option key={option.value} value={option.value}>{label(option.label)}</option>)}
            </select>
          </label>
        ) : null}
        {onCouncilMode && councilEnabled ? (
          <label className={styles.targetSelect}>
            <span className="label">{t("Çalışma biçimi", "Working mode", "工作方式")}</span>
            <select value={shown.options.councilMode ?? "single"} disabled={busy || !isActive} onChange={(e) => onCouncilMode(e.target.value as CouncilMode)} aria-label={t("Promptun nasıl üretileceğini değiştir", "Change how the prompt is generated", "更改提示词生成方式")}>
              {Object.entries(COUNCIL_MODE_LABELS).map(([value, modeLabel]) => <option key={value} value={value}>{label(modeLabel)}</option>)}
            </select>
          </label>
        ) : null}
        <button type="button" className={`btn ${styles.regenerate}`} onClick={onRegenerate} disabled={busy}>
          {t("Promptu yeniden üret", "Regenerate prompt", "重新生成提示词")}
        </button>
      </div>

      <div className={styles.validation} aria-label={t("Üretim ve kalite kontrolü", "Generation and quality review", "生成与质量检查")}>
        <div className={styles.validationHeading}>
          <h3>{t("Üretim ve kontrol bilgisi", "Generation and review details", "生成与检查详情")}</h3>
          <span className={cx(styles.badge, warnings.length ? styles.badgeWarn : isJailbreak ? styles.badgeJb : styles.badgeOk)}>
            {warnings.length ? t(`${warnings.length} kontrol notu`, `${warnings.length} review notes`, `${warnings.length} 条检查备注`) : isJailbreak ? t("JB · kontrol edildi", "JB · reviewed", "JB · 已检查") : t("Kontrol edildi", "Reviewed", "已检查")}
          </span>
        </div>
        <dl className={styles.evidence}>
          <div>
            <dt>{t("Prompt üretimi", "Prompt generation", "提示词生成")}</dt>
            <dd>{generationLabel(shown, t)}</dd>
          </div>
          <div>
            <dt>{t("Kalite incelemesi", "Quality review", "质量评审")}</dt>
            <dd>{critic.llmReviewed ? t("Kural kontrolü + AI eleştirmeni", "Rule checks + AI critic", "规则检查 + AI 评审") : t("Kural kontrolü", "Rule checks", "规则检查")}</dd>
          </div>
          <div>
            <dt>{t("Düzeltmeler", "Corrections", "修正")}</dt>
            <dd>{critic.refined ? t(`${critic.appliedFixes.length} düzeltmeyle yeniden üretildi`, `Regenerated with ${critic.appliedFixes.length} corrections`, `已应用 ${critic.appliedFixes.length} 项修正并重新生成`) : t("Otomatik düzeltme uygulanmadı", "No automatic corrections were applied", "未应用自动修正")}</dd>
          </div>
        </dl>
        {critic.llmError ? <p className={styles.reviewError}>{t("AI incelemesi tamamlanamadı:", "AI review could not be completed:", "AI 评审未能完成：")} {critic.llmError}</p> : null}
        <p className={styles.validationText}>{t("Kontroller, hazırlanan promptun yapısını ve görevle uyumunu değerlendirir.", "Checks assess the prepared prompt's structure and alignment with the task.", "检查会评估生成提示词的结构以及与任务的契合度。")}</p>
        {unresolved.length || critic.appliedFixes.length ? (
          <details className={styles.details}>
            <summary>{t(`Kontrol notları (${unresolved.length} açık, ${critic.appliedFixes.length} düzeltme)`, `Review notes (${unresolved.length} open, ${critic.appliedFixes.length} corrections)`, `检查备注（${unresolved.length} 项未解决，${critic.appliedFixes.length} 项修正）`)}</summary>
            <ul>
              {unresolved.map((issue, i) => (
                <li key={`w${i}`} className={styles.warnItem}>
                  {issue.message}
                </li>
              ))}
              {critic.appliedFixes.map((fix, i) => (
                <li key={`f${i}`} className={styles.fixItem}>
                  {fix}
                </li>
              ))}
            </ul>
          </details>
        ) : null}
      </div>
    </section>
  );
}
